### ISSUE TITLE
yarn add @nervos/chain

### ISSUE THREAD

**Issue by ruizhaoz1** [cryptape/dapp-demos#20]
node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/zxl/github/node_modules/sha3
Output:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**Comment by Keith-CY** [comment]
This error may come with yarn, try `npm install --save @nervos/chain` please.
