### ISSUE TITLE
first-forever: Error: Invalid number of parameters for "undefined". Got 0 expected 1 when deploying

### ISSUE THREAD

**Issue by livc** [cryptape/dapp-demos#28]
Hi,

I'm learning Nervos by following the tutorial `first-forever`, when deploying the contract by `$ npm run deploy`, I get

```
$ npm run deploy

> dont-touch@0.1.0 deploy /Users/zhao/Desktop/dont-touch
> node ./src/contracts/deploy.js

Error: Invalid number of parameters for "undefined". Got 0 expected 1!
    at Object.InvalidNumberOfParams (/Users/zhao/Desktop/dont-touch/node_modules/web3-core-helpers/src/errors.js:32:16)
    at Object._createTxObject (/Users/zhao/Desktop/dont-touch/node_modules/web3-eth-contract/src/index.js:698:22)
    at Contract.deploy (/Users/zhao/Desktop/dont-touch/node_modules/web3-eth-contract/src/index.js:503:33)
    at nervos.appchain.getBlockNumber.then.current (/Users/zhao/Desktop/dont-touch/src/contracts/deploy.js:15:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It seems that there should be an argument in <https://github.com/cryptape/dapp-demos/blob/develop/first-forever/src/contracts/deploy.js#L17> but it's empty.

If I give it an arbitrary parameter, for example
```js
    return myContract
      .deploy({
        data: bytecode,
        arguments: ['1'],
      })
      .send(transaction)
```

I get another error:

```bash
$ npm run deploy

> dont-touch@0.1.0 deploy /Users/zhao/Desktop/dont-touch
> node ./src/contracts/deploy.js

Error: No "from" address specified in neither the given options, nor the default options.
    at Object._executeMethod (/Users/zhao/Desktop/dont-touch/node_modules/@nervos/chain/lib/contract/index.js:76:45)
    at nervos.appchain.getBlockNumber.then.current (/Users/zhao/Desktop/dont-touch/src/contracts/deploy.js:18:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Thanks.

**Comment by Keith-CY** [comment]
> Invalid number of parameters for "undefined". Got 0 expected 1!
Expected Parameters are specified by 'abi', so check your abi please.

> No "from" address specified in neither the given options, nor the default options.
Check if 'from' has been set in `src/contracts/transaction.js`

**Comment by livc** [comment]
@Keith-CY Thanks for the reply!

I find this line <https://github.com/cryptape/dapp-demos/blob/develop/first-forever/src/contracts/transaction.js#L13> was missed in README so I create a PR to fix.
